name: Partial Sync Notion Star

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  partial-sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    steps:
      - uses: actions/checkout@v3  # 更新到更新的版本

      - name: Download cache storage of last build
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: partial-sync.yml
          workflow_conclusion: success
          name: notion-sync-storage
          path: .cache

      - name: Setup Node.js
        uses: actions/setup-node@v4  # 更新到最新版本
        with:
          node-version: 16.x

      # 单独配置 yarn 缓存
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn

      - name: Run Partial Sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TOKEN_OF_GITHUB: ${{ secrets.TOKEN_OF_GITHUB }}
          FULLSYNC_LIMIT: 2000
          PARTIALSYNC_LIMIT: 10
          REPO_TOPICS_LIMIT: 50
        run: npm start

      - uses: actions/upload-artifact@v4
        with:
          name: notion-sync-storage
          path: .cache
